[build-system]
requires = ["setuptools>=61", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "binspected"
description = "Recursive Python introspection engine"
readme = "README.md"
license = { text = "MIT" }
authors = [{ name = "Donald Reilly", email = "donald.reilly.jr@outlook.com" }]
dependencies = []

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools_scm]
write_to = "src/BInspected/_version.py"